// <auto-generated />
using System;
using GarageManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GarageManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210811173912_Created Seed Method")]
    partial class CreatedSeedMethod
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GarageManagementSystem.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "d42eb8c8-2232-406b-9bc0-3859863f064c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ea626e9f-8bf7-48f1-86fd-30ad5d189f69",
                            Email = "admin@gms.ie",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            Name = "Admin",
                            NormalizedEmail = "ADMIN@GMS.IE",
                            NormalizedUserName = "ADMIN@GMS.IE",
                            PasswordHash = "AQAAAAEAACcQAAAAEMz9bWyqbD2nY23BFk96SBhn64ZLC07JbvfUd/dRwrOXdpbT0wiaaOrcSkk1l//GGg==",
                            PhoneNumber = "014569145",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "23ac688c-8701-4335-b597-9f1a2c5877fa",
                            TwoFactorEnabled = false,
                            UserName = "admin@gms.ie"
                        },
                        new
                        {
                            Id = "160453a8-8e19-4f70-9b61-3f6f37d82a3a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4fd928f9-efc5-4ea3-ac52-defefeb913e3",
                            Email = "mechanic1@gms.ie",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            Name = "Mechanic1",
                            NormalizedEmail = "MECHANIC1@GMS.IE",
                            NormalizedUserName = "MECHANIC1@GMS.IE",
                            PasswordHash = "AQAAAAEAACcQAAAAEN70EFGj2hwETRyBu7r6m20vNUJvmgWIjD3xBcc76F4wHyArKD1ZdYRgPLWJlsisUQ==",
                            PhoneNumber = "0834564578",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f2b47994-b60b-4d06-aa88-9474ae0e90fd",
                            TwoFactorEnabled = false,
                            UserName = "mechanic1@gms.ie"
                        },
                        new
                        {
                            Id = "cab9f1df-6d5c-40ae-b05a-be0d0d379f55",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f887abc1-88ba-47a6-a996-c701da722c8a",
                            Email = "mechanic2@gms.ie",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            Name = "Mechanic2",
                            NormalizedEmail = "MECHANIC2@GMS.IE",
                            NormalizedUserName = "MECHANIC2@GMS.IE",
                            PasswordHash = "AQAAAAEAACcQAAAAEFYlRdb9rgLBpSn+TyMD1vvxpDABeuNCprPh1TFI8kT+w3QEMqhQCBXWhsqTCTqROw==",
                            PhoneNumber = "0834564536",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f5add130-1829-4155-b12d-4eab659a5cac",
                            TwoFactorEnabled = false,
                            UserName = "mechanic2@gms.ie"
                        },
                        new
                        {
                            Id = "990d5d6b-e4b1-4978-accc-5065754d1632",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "baf4859f-767a-4ea1-92ac-2c1c30558c6a",
                            Email = "mechanic3@gms.ie",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            Name = "Mechanic3",
                            NormalizedEmail = "MECHANIC3@GMS.IE",
                            NormalizedUserName = "MECHANIC3@GMS.IE",
                            PasswordHash = "AQAAAAEAACcQAAAAEKbTwf8qFDYFQWFEmxA+xB0yYhVqRXFQuJEYFcqSrdXPeAMhhNK2VVc6DiflOUJENg==",
                            PhoneNumber = "0834564597",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d3b60a4b-04f1-46e3-91db-ca101e9c9c80",
                            TwoFactorEnabled = false,
                            UserName = "mechanic3@gms.ie"
                        },
                        new
                        {
                            Id = "98857515-b584-464e-850c-5047904de7f7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d38e1f40-44b0-4080-a4a3-004e005db08f",
                            Email = "mechanic4@gms.ie",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            Name = "Mechanic4",
                            NormalizedEmail = "MECHANIC4@GMS.IE",
                            NormalizedUserName = "MECHANIC4@GMS.IE",
                            PasswordHash = "AQAAAAEAACcQAAAAED2NECljyc9oqFYBXdJ0RTa1ZjcfEgs58DC+184CDIBe4SvVfF/yUyd9v+GvDhymrw==",
                            PhoneNumber = "0834564571",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bc98965d-2e52-4538-a4bc-8952c611a398",
                            TwoFactorEnabled = false,
                            UserName = "mechanic4@gms.ie"
                        });
                });

            modelBuilder.Entity("GarageManagementSystem.Models.Booking", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BookingType")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("MechanicId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MechanicId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("GarageManagementSystem.Models.Invoice", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BookingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Licence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vehicle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("GarageManagementSystem.Models.InvoiceService", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("InvoiceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceService");
                });

            modelBuilder.Entity("GarageManagementSystem.Models.Part", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Group")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Part");

                    b.HasData(
                        new
                        {
                            Id = "ddb41b99-4711-42df-a4a9-eed637f6ccef",
                            Deleted = false,
                            Group = "Electric",
                            Name = "Alternator",
                            Value = 120.0m
                        },
                        new
                        {
                            Id = "866e727e-b0f9-4e9f-8bc3-ed8f8bbfddb8",
                            Deleted = false,
                            Group = "Electric",
                            Name = "Battery",
                            Value = 50.5m
                        },
                        new
                        {
                            Id = "971e881a-ce0b-448b-b7f0-a77d6ea9d19e",
                            Deleted = false,
                            Group = "Electric",
                            Name = "Battery Cable",
                            Value = 20.2m
                        },
                        new
                        {
                            Id = "bf5d835f-bc67-425a-94c1-a4802d1790fa",
                            Deleted = false,
                            Group = "Electric",
                            Name = "Voltage regulator",
                            Value = 3.1m
                        },
                        new
                        {
                            Id = "8ca38b99-1433-493f-a45a-985622309527",
                            Deleted = false,
                            Group = "Electric",
                            Name = "Distilled Water",
                            Value = 5.4m
                        },
                        new
                        {
                            Id = "b1ca8ec6-cbe6-4c0c-aa36-c22d922ba029",
                            Deleted = false,
                            Group = "Ignition",
                            Name = "Sparking cable",
                            Value = 10.95m
                        },
                        new
                        {
                            Id = "1c78fff5-d3cf-4d51-986f-e4423d7fdeb0",
                            Deleted = false,
                            Group = "Ignition",
                            Name = "Ignition Coil",
                            Value = 8.45m
                        },
                        new
                        {
                            Id = "548a06d3-e329-4706-8881-cba34905a531",
                            Deleted = false,
                            Group = "Ignition",
                            Name = "Ignition box",
                            Value = 130.5m
                        },
                        new
                        {
                            Id = "632875ca-fe68-4d2b-b581-3e0187cb9fab",
                            Deleted = false,
                            Group = "Ignition",
                            Name = "Distributor",
                            Value = 10.95m
                        },
                        new
                        {
                            Id = "1055c072-599d-403d-a70a-3e5b2b80cf08",
                            Deleted = false,
                            Group = "Lighting",
                            Name = "Fog light",
                            Value = 4.95m
                        },
                        new
                        {
                            Id = "6bb33ce9-170d-4eb3-b687-5727a27fb9e0",
                            Deleted = false,
                            Group = "Lighting",
                            Name = "Headlight",
                            Value = 24.7m
                        },
                        new
                        {
                            Id = "f620ac69-aa4c-4cb3-ae11-35eb7237b888",
                            Deleted = false,
                            Group = "Lighting",
                            Name = "Spotlight",
                            Value = 9.95m
                        },
                        new
                        {
                            Id = "8f2fc967-bba7-4997-a05b-f931d172433e",
                            Deleted = false,
                            Group = "Lighting",
                            Name = "Turn signal",
                            Value = 4.75m
                        },
                        new
                        {
                            Id = "2108e839-9a2a-45e4-9709-719c96e40006",
                            Deleted = false,
                            Group = "Lighting",
                            Name = "Brake light",
                            Value = 5.85m
                        },
                        new
                        {
                            Id = "8ad0856f-f068-4b4d-8e90-0f54c447df4b",
                            Deleted = false,
                            Group = "Lighting",
                            Name = "Interior light",
                            Value = 8.0m
                        },
                        new
                        {
                            Id = "31a8381d-361a-4a46-9f85-3a7c297a6920",
                            Deleted = false,
                            Group = "Sensor",
                            Name = "Fuel level sensor",
                            Value = 25.55m
                        },
                        new
                        {
                            Id = "eb9e8c2e-5f7a-474c-aa05-e919d4ef9a35",
                            Deleted = false,
                            Group = "Sensor",
                            Name = "Airbag sensors",
                            Value = 20.15m
                        },
                        new
                        {
                            Id = "2b4a765c-b48a-40c7-877a-a2c7ebcfb549",
                            Deleted = false,
                            Group = "Sensor",
                            Name = "Oil level sensor",
                            Value = 15.0m
                        },
                        new
                        {
                            Id = "50b02451-d226-41dc-98ab-557dc02918f4",
                            Deleted = false,
                            Group = "Sensor",
                            Name = "Oil pressure sensor",
                            Value = 30.99m
                        },
                        new
                        {
                            Id = "0b257d41-3c15-47cc-9c02-0142d7ad3300",
                            Deleted = false,
                            Group = "Sensor",
                            Name = "Coolant temperature sensor",
                            Value = 20.65m
                        },
                        new
                        {
                            Id = "9ea889bd-1e82-4178-8092-cdc0d838d32c",
                            Deleted = false,
                            Group = "Miscellaneous",
                            Name = "Air bag control module",
                            Value = 56.79m
                        },
                        new
                        {
                            Id = "42de5c62-55aa-4603-a4ac-87d7092e6d01",
                            Deleted = false,
                            Group = "Miscellaneous",
                            Name = "Alarm and siren",
                            Value = 25.45m
                        },
                        new
                        {
                            Id = "94cd0a5c-3f90-421a-9558-ac2a7c3954a2",
                            Deleted = false,
                            Group = "Miscellaneous",
                            Name = "Central locking system",
                            Value = 40.9m
                        },
                        new
                        {
                            Id = "2c6d4a5a-8166-47ea-8094-b837fcd2c515",
                            Deleted = false,
                            Group = "Miscellaneous",
                            Name = "Fuse",
                            Value = 1.2m
                        },
                        new
                        {
                            Id = "68e6630f-c83b-4c18-a362-808422933bbf",
                            Deleted = false,
                            Group = "Miscellaneous",
                            Name = "Fuse Box",
                            Value = 11.55m
                        },
                        new
                        {
                            Id = "4a5b90be-87fb-4c50-8c83-988f685a0a8d",
                            Deleted = false,
                            Group = "Miscellaneous",
                            Name = "GPS",
                            Value = 10.95m
                        },
                        new
                        {
                            Id = "01b99afb-8cce-45e6-a728-7bf21c536b02",
                            Deleted = false,
                            Group = "Miscellaneous",
                            Name = "Speed controller",
                            Value = 10.95m
                        },
                        new
                        {
                            Id = "eb73dcd7-b73e-498e-ac29-eebd6c7ae816",
                            Deleted = false,
                            Group = "Miscellaneous",
                            Name = "Transmission computer",
                            Value = 10.95m
                        },
                        new
                        {
                            Id = "633990ed-8a97-46d4-8cd2-9dafe70611e4",
                            Deleted = false,
                            Group = "Miscellaneous",
                            Name = "Engine computer and management system",
                            Value = 10.95m
                        },
                        new
                        {
                            Id = "fdb3f313-f602-438a-92f9-9149f19fda7b",
                            Deleted = false,
                            Group = "Braking System",
                            Name = "Anti-lock braking system (ABS) ",
                            Value = 150.45m
                        },
                        new
                        {
                            Id = "f83dc4b4-8b53-428e-89f5-07c2227ee9fc",
                            Deleted = false,
                            Group = "Braking System",
                            Name = "Brake disc",
                            Value = 10.0m
                        },
                        new
                        {
                            Id = "16340c2f-f47a-45bd-a9cb-e398ed8ce2a8",
                            Deleted = false,
                            Group = "Braking System",
                            Name = "Brake Fluid",
                            Value = 8.45m
                        },
                        new
                        {
                            Id = "d5977c81-b10e-4fab-8711-7475b86e3980",
                            Deleted = false,
                            Group = "Braking System",
                            Name = "Brake pedal",
                            Value = 30.95m
                        },
                        new
                        {
                            Id = "b7df2393-004d-413c-96e3-f3d4ff1da982",
                            Deleted = false,
                            Group = "Braking System",
                            Name = "Brake warning light",
                            Value = 3.5m
                        },
                        new
                        {
                            Id = "e53eedc9-6029-4dcc-81e4-23b5a57c8a0e",
                            Deleted = false,
                            Group = "Braking System",
                            Name = "Park brake",
                            Value = 36.45m
                        },
                        new
                        {
                            Id = "419546c7-fc0f-4b71-bf81-d5144c0d7f36",
                            Deleted = false,
                            Group = "Braking System",
                            Name = "Tyre",
                            Value = 59.99m
                        },
                        new
                        {
                            Id = "fa4228aa-5e40-4fca-9ee7-b7d35402330a",
                            Deleted = false,
                            Group = "Braking System",
                            Name = "Brake pump",
                            Value = 24.89m
                        },
                        new
                        {
                            Id = "da3d5e2f-3d2e-4284-8273-6fbcd8e9e583",
                            Deleted = false,
                            Group = "Engine",
                            Name = "Diesel engine",
                            Value = 1647.8m
                        },
                        new
                        {
                            Id = "397a1635-5318-488f-8b3d-e4c8450d25e7",
                            Deleted = false,
                            Group = "Engine",
                            Name = "Cylinder head",
                            Value = 85.4m
                        },
                        new
                        {
                            Id = "6c631c29-91b6-437c-90a3-a323c04403e2",
                            Deleted = false,
                            Group = "Engine",
                            Name = "Piston",
                            Value = 35.4m
                        },
                        new
                        {
                            Id = "4f41669f-bdf2-4712-b90c-e7050c19f9f5",
                            Deleted = false,
                            Group = "Engine",
                            Name = "Starter motor",
                            Value = 28.6m
                        },
                        new
                        {
                            Id = "87dfb7ac-910e-4a2e-908f-c112206a52be",
                            Deleted = false,
                            Group = "Engine",
                            Name = "Petrol engine (gasoline engine)",
                            Value = 789.5m
                        },
                        new
                        {
                            Id = "7ac99a7f-f9c5-400c-9ae5-8bef95eedd1d",
                            Deleted = false,
                            Group = "Cooling",
                            Name = "Radiator",
                            Value = 55.1m
                        },
                        new
                        {
                            Id = "c5316643-bdd9-4d25-93b2-abaf5240ac57",
                            Deleted = false,
                            Group = "Cooling",
                            Name = "Cooling fan",
                            Value = 29.9m
                        },
                        new
                        {
                            Id = "19efef04-a680-499b-b609-4c2b60f39e6c",
                            Deleted = false,
                            Group = "Cooling",
                            Name = "Water tank",
                            Value = 35.4m
                        },
                        new
                        {
                            Id = "53b02644-b94a-453b-a7bc-efc43626997b",
                            Deleted = false,
                            Group = "Filter",
                            Name = "Oil filter",
                            Value = 15.00m
                        },
                        new
                        {
                            Id = "e204a036-4bb6-4f05-bc2c-8b66d2d598f2",
                            Deleted = false,
                            Group = "Filter",
                            Name = "Air filter",
                            Value = 11.45m
                        },
                        new
                        {
                            Id = "c68f7260-262f-4118-8e54-5154cead0106",
                            Deleted = false,
                            Group = "Filter",
                            Name = "Fuel filter",
                            Value = 17.5m
                        });
                });

            modelBuilder.Entity("GarageManagementSystem.Models.Service", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Group")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Service");

                    b.HasData(
                        new
                        {
                            Id = "ffa83757-2c4d-459a-b973-0719066dae02",
                            Deleted = false,
                            Group = "Main",
                            Name = "Annual Service",
                            Value = 120.0m
                        },
                        new
                        {
                            Id = "31096fae-7726-4aa9-85d2-97f8c075c9ab",
                            Deleted = false,
                            Group = "Main",
                            Name = "Major Service",
                            Value = 120.0m
                        },
                        new
                        {
                            Id = "5d1919ec-6e44-44d0-9710-f2b23c0b2c22",
                            Deleted = false,
                            Group = "Main",
                            Name = "Repair / Fault",
                            Value = 120.0m
                        },
                        new
                        {
                            Id = "020abf47-bb76-45b8-90b0-d960ccd65226",
                            Deleted = false,
                            Group = "Main",
                            Name = "Major Repair",
                            Value = 120.0m
                        });
                });

            modelBuilder.Entity("GarageManagementSystem.Models.Vehicle", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("EngineType")
                        .HasColumnType("int");

                    b.Property<string>("Licence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Make")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Vehicle");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "e3d4f4a2-1c98-486d-bc8d-1773e3766bb4",
                            ConcurrencyStamp = "7d36eb1e-f28b-4984-b8f8-ccd44b6f11c9",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "b09f1e6f-0574-4589-9c08-44d22a208054",
                            ConcurrencyStamp = "aaeb9d55-3071-40d0-8d46-8c1b121751fb",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        },
                        new
                        {
                            Id = "ef38b05c-8be4-4162-a344-1eec9d231943",
                            ConcurrencyStamp = "2d137420-c535-4fb7-9f32-801e44f4c7d4",
                            Name = "Mechanic",
                            NormalizedName = "MECHANIC"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "d42eb8c8-2232-406b-9bc0-3859863f064c",
                            RoleId = "e3d4f4a2-1c98-486d-bc8d-1773e3766bb4"
                        },
                        new
                        {
                            UserId = "160453a8-8e19-4f70-9b61-3f6f37d82a3a",
                            RoleId = "ef38b05c-8be4-4162-a344-1eec9d231943"
                        },
                        new
                        {
                            UserId = "cab9f1df-6d5c-40ae-b05a-be0d0d379f55",
                            RoleId = "ef38b05c-8be4-4162-a344-1eec9d231943"
                        },
                        new
                        {
                            UserId = "990d5d6b-e4b1-4978-accc-5065754d1632",
                            RoleId = "ef38b05c-8be4-4162-a344-1eec9d231943"
                        },
                        new
                        {
                            UserId = "98857515-b584-464e-850c-5047904de7f7",
                            RoleId = "ef38b05c-8be4-4162-a344-1eec9d231943"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("GarageManagementSystem.Models.Booking", b =>
                {
                    b.HasOne("GarageManagementSystem.Models.ApplicationUser", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GarageManagementSystem.Models.ApplicationUser", "Mechanic")
                        .WithMany()
                        .HasForeignKey("MechanicId");

                    b.HasOne("GarageManagementSystem.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Mechanic");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("GarageManagementSystem.Models.Invoice", b =>
                {
                    b.HasOne("GarageManagementSystem.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("GarageManagementSystem.Models.InvoiceService", b =>
                {
                    b.HasOne("GarageManagementSystem.Models.Invoice", null)
                        .WithMany("InvoiceServices")
                        .HasForeignKey("InvoiceId");
                });

            modelBuilder.Entity("GarageManagementSystem.Models.Vehicle", b =>
                {
                    b.HasOne("GarageManagementSystem.Models.ApplicationUser", null)
                        .WithMany("Vehicles")
                        .HasForeignKey("ApplicationUserId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GarageManagementSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GarageManagementSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GarageManagementSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GarageManagementSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GarageManagementSystem.Models.ApplicationUser", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("GarageManagementSystem.Models.Invoice", b =>
                {
                    b.Navigation("InvoiceServices");
                });
#pragma warning restore 612, 618
        }
    }
}
