// <auto-generated />
using System;
using GarageManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GarageManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210815174242_Seed Services")]
    partial class SeedServices
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GarageManagementSystem.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "d42eb8c8-2232-406b-9bc0-3859863f064c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "db627788-fd9c-49aa-99ba-481b26ca9be4",
                            Email = "admin@gms.ie",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            Name = "Admin",
                            NormalizedEmail = "ADMIN@GMS.IE",
                            NormalizedUserName = "ADMIN@GMS.IE",
                            PasswordHash = "AQAAAAEAACcQAAAAEH5Xj5Hx6fN5R+zITrCFFeIzrU060zxMUQc8d5jMzq0ENuPZdl8FfuJipEXzSly6Kw==",
                            PhoneNumber = "014569145",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3c00b3e2-c5ff-4e8b-a51a-729235fba9d7",
                            TwoFactorEnabled = false,
                            UserName = "admin@gms.ie"
                        },
                        new
                        {
                            Id = "160453a8-8e19-4f70-9b61-3f6f37d82a3a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9a2a1944-b55d-435a-97a4-e7091f2556e3",
                            Email = "mechanic1@gms.ie",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            Name = "Mechanic1",
                            NormalizedEmail = "MECHANIC1@GMS.IE",
                            NormalizedUserName = "MECHANIC1@GMS.IE",
                            PasswordHash = "AQAAAAEAACcQAAAAEOxmMMTDfMvC4akpGDN5dnTU/E7aFmGOJuN8Z7oaUzVuYqlJoUuLZTN9MLtY/i5ZNg==",
                            PhoneNumber = "0834564578",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9f09da7a-0d7b-4c85-b590-1adf749f69f0",
                            TwoFactorEnabled = false,
                            UserName = "mechanic1@gms.ie"
                        },
                        new
                        {
                            Id = "cab9f1df-6d5c-40ae-b05a-be0d0d379f55",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "88594513-b5fb-42ca-b316-e3d9f0254d0a",
                            Email = "mechanic2@gms.ie",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            Name = "Mechanic2",
                            NormalizedEmail = "MECHANIC2@GMS.IE",
                            NormalizedUserName = "MECHANIC2@GMS.IE",
                            PasswordHash = "AQAAAAEAACcQAAAAEJB6Oz7f5xsNOWTAPdbQ94uSY0/WhC2F0fnuHfnRta0wcaBi2t/RSFEL/5M/tz6+ZA==",
                            PhoneNumber = "0834564536",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "505939ed-9e3d-4159-97fb-2f2eeadf823d",
                            TwoFactorEnabled = false,
                            UserName = "mechanic2@gms.ie"
                        },
                        new
                        {
                            Id = "990d5d6b-e4b1-4978-accc-5065754d1632",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2c88cfce-696f-42e0-9bf6-11ef28360701",
                            Email = "mechanic3@gms.ie",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            Name = "Mechanic3",
                            NormalizedEmail = "MECHANIC3@GMS.IE",
                            NormalizedUserName = "MECHANIC3@GMS.IE",
                            PasswordHash = "AQAAAAEAACcQAAAAEBNih0ew8n8cakmJWcIZ4KEd9av+m+n23QSCezVLAFUgMPSvefRaP580mG7ETpb0fQ==",
                            PhoneNumber = "0834564597",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "51869a01-c8b8-4634-b1fc-5f43fe18ebdd",
                            TwoFactorEnabled = false,
                            UserName = "mechanic3@gms.ie"
                        },
                        new
                        {
                            Id = "98857515-b584-464e-850c-5047904de7f7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2832d220-146a-4d04-9a6d-86848d8b44cc",
                            Email = "mechanic4@gms.ie",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            Name = "Mechanic4",
                            NormalizedEmail = "MECHANIC4@GMS.IE",
                            NormalizedUserName = "MECHANIC4@GMS.IE",
                            PasswordHash = "AQAAAAEAACcQAAAAEI7T8eDILnh98X2gSHx1JXmi/fxcxZ1/U+hMdJAiFTd3NcyVT3UzQ6HB377b8bPpdQ==",
                            PhoneNumber = "0834564571",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "46905669-fd47-4594-98fd-671b457f5644",
                            TwoFactorEnabled = false,
                            UserName = "mechanic4@gms.ie"
                        });
                });

            modelBuilder.Entity("GarageManagementSystem.Models.Booking", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BookingType")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("MechanicId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MechanicId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("GarageManagementSystem.Models.Invoice", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BookingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Licence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vehicle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("GarageManagementSystem.Models.InvoicePart", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("InvoiceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoicePart");
                });

            modelBuilder.Entity("GarageManagementSystem.Models.InvoiceService", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("InvoiceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceService");
                });

            modelBuilder.Entity("GarageManagementSystem.Models.Part", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Group")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Part");

                    b.HasData(
                        new
                        {
                            Id = "d28c751a-cda2-42a2-9b87-d1b1d8aeb663",
                            Deleted = false,
                            Group = "Electric",
                            Name = "Alternator",
                            Value = 120.0m
                        },
                        new
                        {
                            Id = "3dea9c64-e7e4-4b9e-b477-b6c55afe5591",
                            Deleted = false,
                            Group = "Electric",
                            Name = "Battery",
                            Value = 50.5m
                        },
                        new
                        {
                            Id = "0772a147-e86b-4bcf-ad4f-7aa530e85a3c",
                            Deleted = false,
                            Group = "Electric",
                            Name = "Battery Cable",
                            Value = 20.2m
                        },
                        new
                        {
                            Id = "7b35769b-1356-4db2-8a72-cfc0a5420650",
                            Deleted = false,
                            Group = "Electric",
                            Name = "Voltage regulator",
                            Value = 3.1m
                        },
                        new
                        {
                            Id = "538b39df-9999-4652-bec4-43e5dc6aa678",
                            Deleted = false,
                            Group = "Electric",
                            Name = "Distilled Water",
                            Value = 5.4m
                        },
                        new
                        {
                            Id = "0360bdf0-1834-4aa6-a33c-4f10761d2632",
                            Deleted = false,
                            Group = "Ignition",
                            Name = "Sparking cable",
                            Value = 10.95m
                        },
                        new
                        {
                            Id = "605fac19-cdb4-441c-8b0d-5297ea8927ef",
                            Deleted = false,
                            Group = "Ignition",
                            Name = "Ignition Coil",
                            Value = 8.45m
                        },
                        new
                        {
                            Id = "0abd32ac-6246-426b-8c3e-563936cdbc9e",
                            Deleted = false,
                            Group = "Ignition",
                            Name = "Ignition box",
                            Value = 130.5m
                        },
                        new
                        {
                            Id = "5609624a-939e-4c41-85f3-55e023c71360",
                            Deleted = false,
                            Group = "Ignition",
                            Name = "Distributor",
                            Value = 10.95m
                        },
                        new
                        {
                            Id = "10bf5799-9120-44f4-9b6c-cb44d2f995cf",
                            Deleted = false,
                            Group = "Lighting",
                            Name = "Fog light",
                            Value = 4.95m
                        },
                        new
                        {
                            Id = "1022c4cd-375d-4d88-9dd6-7689b5aaec8d",
                            Deleted = false,
                            Group = "Lighting",
                            Name = "Headlight",
                            Value = 24.7m
                        },
                        new
                        {
                            Id = "f4f05bf7-235c-4687-820d-86bf2bfdde49",
                            Deleted = false,
                            Group = "Lighting",
                            Name = "Spotlight",
                            Value = 9.95m
                        },
                        new
                        {
                            Id = "2f7ae64e-e06d-4391-a814-76659e1a4911",
                            Deleted = false,
                            Group = "Lighting",
                            Name = "Turn signal",
                            Value = 4.75m
                        },
                        new
                        {
                            Id = "65d7befb-46c2-4a45-97bc-b4af572b3bdd",
                            Deleted = false,
                            Group = "Lighting",
                            Name = "Brake light",
                            Value = 5.85m
                        },
                        new
                        {
                            Id = "6d376b45-1b6e-4ae5-8c36-62f9fbd17653",
                            Deleted = false,
                            Group = "Lighting",
                            Name = "Interior light",
                            Value = 8.0m
                        },
                        new
                        {
                            Id = "627f93e4-0263-4f13-abaf-4bdd83622e06",
                            Deleted = false,
                            Group = "Sensor",
                            Name = "Fuel level sensor",
                            Value = 25.55m
                        },
                        new
                        {
                            Id = "24482bc5-052d-44d2-96ab-2ebf71e29398",
                            Deleted = false,
                            Group = "Sensor",
                            Name = "Airbag sensors",
                            Value = 20.15m
                        },
                        new
                        {
                            Id = "e34137cd-e457-4758-ace8-9ef441c1661a",
                            Deleted = false,
                            Group = "Sensor",
                            Name = "Oil level sensor",
                            Value = 15.0m
                        },
                        new
                        {
                            Id = "91cf18f8-245c-48c7-bddf-3ede1488954b",
                            Deleted = false,
                            Group = "Sensor",
                            Name = "Oil pressure sensor",
                            Value = 30.99m
                        },
                        new
                        {
                            Id = "0830b7a1-342f-49e6-a0e5-515bb66f2093",
                            Deleted = false,
                            Group = "Sensor",
                            Name = "Coolant temperature sensor",
                            Value = 20.65m
                        },
                        new
                        {
                            Id = "581b0369-b94f-4581-b09d-4aa97bbacb8c",
                            Deleted = false,
                            Group = "Miscellaneous",
                            Name = "Air bag control module",
                            Value = 56.79m
                        },
                        new
                        {
                            Id = "0469d46f-7469-4714-b043-230a60fa5a71",
                            Deleted = false,
                            Group = "Miscellaneous",
                            Name = "Alarm and siren",
                            Value = 25.45m
                        },
                        new
                        {
                            Id = "d28fd34a-6793-4ac8-a5b0-6d23854dc800",
                            Deleted = false,
                            Group = "Miscellaneous",
                            Name = "Central locking system",
                            Value = 40.9m
                        },
                        new
                        {
                            Id = "e3fdc36a-2afb-4d1a-991a-22515c9c6078",
                            Deleted = false,
                            Group = "Miscellaneous",
                            Name = "Fuse",
                            Value = 1.2m
                        },
                        new
                        {
                            Id = "14f8808a-6fa9-4d32-8f36-4cc298cb2a3e",
                            Deleted = false,
                            Group = "Miscellaneous",
                            Name = "Fuse Box",
                            Value = 11.55m
                        },
                        new
                        {
                            Id = "8398cc49-90d7-475d-ba2f-4dd242d89fa3",
                            Deleted = false,
                            Group = "Miscellaneous",
                            Name = "GPS",
                            Value = 10.95m
                        },
                        new
                        {
                            Id = "8983ae42-6b6a-46a1-a9fb-44cff51833e6",
                            Deleted = false,
                            Group = "Miscellaneous",
                            Name = "Speed controller",
                            Value = 10.95m
                        },
                        new
                        {
                            Id = "e79efdc1-108d-4244-8105-061307091402",
                            Deleted = false,
                            Group = "Miscellaneous",
                            Name = "Transmission computer",
                            Value = 10.95m
                        },
                        new
                        {
                            Id = "bb5db953-814f-4b48-a195-ea1055d753d4",
                            Deleted = false,
                            Group = "Miscellaneous",
                            Name = "Engine computer and management system",
                            Value = 10.95m
                        },
                        new
                        {
                            Id = "b6d31468-041f-465c-bb21-905f5d8f00b8",
                            Deleted = false,
                            Group = "Braking System",
                            Name = "Anti-lock braking system (ABS) ",
                            Value = 150.45m
                        },
                        new
                        {
                            Id = "1db744f4-62b5-4ae4-96db-8e888b1c9249",
                            Deleted = false,
                            Group = "Braking System",
                            Name = "Brake disc",
                            Value = 10.0m
                        },
                        new
                        {
                            Id = "c16b3cc0-7574-404a-9a32-a5b6bb7a5ec1",
                            Deleted = false,
                            Group = "Braking System",
                            Name = "Brake Fluid",
                            Value = 8.45m
                        },
                        new
                        {
                            Id = "c2eaeeb0-359e-402b-9b1e-3abeb8421af8",
                            Deleted = false,
                            Group = "Braking System",
                            Name = "Brake pedal",
                            Value = 30.95m
                        },
                        new
                        {
                            Id = "d91c54fe-7e53-4f69-bfc3-b5a48bd0d78c",
                            Deleted = false,
                            Group = "Braking System",
                            Name = "Brake warning light",
                            Value = 3.5m
                        },
                        new
                        {
                            Id = "6671de5b-e044-47cd-b6ed-325a470dd512",
                            Deleted = false,
                            Group = "Braking System",
                            Name = "Park brake",
                            Value = 36.45m
                        },
                        new
                        {
                            Id = "d180ed84-19c8-46b1-a016-1a1e2b5a0ad9",
                            Deleted = false,
                            Group = "Braking System",
                            Name = "Tyre",
                            Value = 59.99m
                        },
                        new
                        {
                            Id = "97d6ee62-64d8-46fb-b135-d3edf3302b3f",
                            Deleted = false,
                            Group = "Braking System",
                            Name = "Brake pump",
                            Value = 24.89m
                        },
                        new
                        {
                            Id = "243fc8b7-0b07-420c-940d-9c4bcc60f9bc",
                            Deleted = false,
                            Group = "Engine",
                            Name = "Diesel engine",
                            Value = 1647.8m
                        },
                        new
                        {
                            Id = "158b8154-fb41-4a18-8726-c4edd80b028b",
                            Deleted = false,
                            Group = "Engine",
                            Name = "Cylinder head",
                            Value = 85.4m
                        },
                        new
                        {
                            Id = "fee0b15b-bb34-4d46-9f86-a6edf040359f",
                            Deleted = false,
                            Group = "Engine",
                            Name = "Piston",
                            Value = 35.4m
                        },
                        new
                        {
                            Id = "899ee99b-9e16-483d-9dd6-d7cf00823aee",
                            Deleted = false,
                            Group = "Engine",
                            Name = "Starter motor",
                            Value = 28.6m
                        },
                        new
                        {
                            Id = "d59696db-e796-4a0c-8452-73b6b1941d4e",
                            Deleted = false,
                            Group = "Engine",
                            Name = "Petrol engine (gasoline engine)",
                            Value = 789.5m
                        },
                        new
                        {
                            Id = "158f4a0d-81a6-4efd-94c4-9e37942b304f",
                            Deleted = false,
                            Group = "Cooling",
                            Name = "Radiator",
                            Value = 55.1m
                        },
                        new
                        {
                            Id = "d831d75e-d4f0-4320-b643-94a1dc7d5e93",
                            Deleted = false,
                            Group = "Cooling",
                            Name = "Cooling fan",
                            Value = 29.9m
                        },
                        new
                        {
                            Id = "92ac9eef-1ce2-48d8-b019-27604b97f54f",
                            Deleted = false,
                            Group = "Cooling",
                            Name = "Water tank",
                            Value = 35.4m
                        },
                        new
                        {
                            Id = "66143576-4333-430d-92ca-fcd9990204e4",
                            Deleted = false,
                            Group = "Filter",
                            Name = "Oil filter",
                            Value = 15.00m
                        },
                        new
                        {
                            Id = "f5882a87-276e-4a6b-a76a-6d0c8a26d7b7",
                            Deleted = false,
                            Group = "Filter",
                            Name = "Air filter",
                            Value = 11.45m
                        },
                        new
                        {
                            Id = "7720e1a8-6cd0-4b02-9815-c8182bd0e8aa",
                            Deleted = false,
                            Group = "Filter",
                            Name = "Fuel filter",
                            Value = 17.5m
                        });
                });

            modelBuilder.Entity("GarageManagementSystem.Models.Service", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Group")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Service");

                    b.HasData(
                        new
                        {
                            Id = "92853e40-7394-4d2f-b7b6-5eb83fc4bfd7",
                            Deleted = false,
                            Group = "Main",
                            Name = "Annual Service",
                            Value = 120.0m
                        },
                        new
                        {
                            Id = "32aa34d5-e40e-4bbb-a7f0-ca578f3a4709",
                            Deleted = false,
                            Group = "Main",
                            Name = "Major Service",
                            Value = 120.0m
                        },
                        new
                        {
                            Id = "03b96d1a-cf72-4fab-a10e-c91d27020c64",
                            Deleted = false,
                            Group = "Main",
                            Name = "Repair / Fault",
                            Value = 120.0m
                        },
                        new
                        {
                            Id = "646748b9-226f-4f69-b7f0-ce42bcabd9f5",
                            Deleted = false,
                            Group = "Main",
                            Name = "Major Repair",
                            Value = 120.0m
                        },
                        new
                        {
                            Id = "e792e493-aef3-4180-b6c6-01e039090e46",
                            Deleted = false,
                            Group = "Brake",
                            Name = "Front And Rear Disc Brake Pad Replacement",
                            Value = 35.0m
                        },
                        new
                        {
                            Id = "dc3d13d1-b318-475d-be9a-08412fb07604",
                            Deleted = false,
                            Group = "Brake",
                            Name = "Brake Cylinder Replacement",
                            Value = 45.0m
                        },
                        new
                        {
                            Id = "8fa18b93-f9be-4f45-998a-4f6645811074",
                            Deleted = false,
                            Group = "Brake",
                            Name = "Brake Master Cylinder Replacement Or Reconditioning",
                            Value = 58.60m
                        },
                        new
                        {
                            Id = "d79a4c20-60bd-4371-bd37-a1283824e5ab",
                            Deleted = false,
                            Group = "Brake",
                            Name = "Brake Caliper Overhaul",
                            Value = 13.0m
                        },
                        new
                        {
                            Id = "41329804-8afb-4007-81d5-b8147e1b5dbc",
                            Deleted = false,
                            Group = "Brake",
                            Name = "Brake Fluid Replacement",
                            Value = 16.05m
                        },
                        new
                        {
                            Id = "274887ea-aa95-4f06-b1c2-5318973031e8",
                            Deleted = false,
                            Group = "Brake",
                            Name = "Brake Adjustment",
                            Value = 25.0m
                        },
                        new
                        {
                            Id = "d0951620-6d6b-4ae0-8756-eaa7c1ad445b",
                            Deleted = false,
                            Group = "Brake",
                            Name = "Brake Pipe Replacement",
                            Value = 34.50m
                        },
                        new
                        {
                            Id = "4fd0d25b-52f3-4156-ba0e-a717a517bce0",
                            Deleted = false,
                            Group = "Brake",
                            Name = "Brake Shoe Replacement",
                            Value = 49.0m
                        },
                        new
                        {
                            Id = "e4917606-e346-4be0-a598-6fed440fccdf",
                            Deleted = false,
                            Group = "Brake",
                            Name = "Abs Module Replacement And Diagnosing",
                            Value = 55.40m
                        },
                        new
                        {
                            Id = "15cb1893-aba9-4f84-b952-aaab8acfda37",
                            Deleted = false,
                            Group = "Electrical Repairs",
                            Name = "Computer Fault Scaning And Diagnosis",
                            Value = 55.40m
                        },
                        new
                        {
                            Id = "aef5912d-572d-4bbe-bf0a-ff6012db0c38",
                            Deleted = false,
                            Group = "Electrical Repairs",
                            Name = "Starter Motor Replacement",
                            Value = 55.40m
                        },
                        new
                        {
                            Id = "6d95778b-91ed-4202-873a-69f47db490ef",
                            Deleted = false,
                            Group = "Electrical Repairs",
                            Name = "Charging System Testing",
                            Value = 55.40m
                        },
                        new
                        {
                            Id = "00805ac7-b198-46e9-943e-da8aa14213e6",
                            Deleted = false,
                            Group = "Electrical Repairs",
                            Name = "Alternator Replacement",
                            Value = 55.40m
                        },
                        new
                        {
                            Id = "a2313586-b479-475e-b29e-4409f09761d7",
                            Deleted = false,
                            Group = "Electrical Repairs",
                            Name = "Small Wiring Repairs",
                            Value = 55.40m
                        },
                        new
                        {
                            Id = "e21d8ec7-3b26-4c2c-9b82-1d0e3751fb12",
                            Deleted = false,
                            Group = "Electrical Repairs",
                            Name = "Electric Window Repairs",
                            Value = 55.40m
                        },
                        new
                        {
                            Id = "95c631c1-6a62-43f1-97d7-a904dca527fd",
                            Deleted = false,
                            Group = "Electrical Repairs",
                            Name = "Head Light and Tail Light Repairs",
                            Value = 55.40m
                        },
                        new
                        {
                            Id = "a41a1ffa-319c-4092-8195-a3ae583bd92b",
                            Deleted = false,
                            Group = "Electrical Repairs",
                            Name = "Ignition Testing",
                            Value = 55.40m
                        },
                        new
                        {
                            Id = "c5d2c617-034c-4a4d-b5e5-1b7e4462e57d",
                            Deleted = false,
                            Group = "Electrical Repairs",
                            Name = "Battery Testing and Replacing",
                            Value = 55.40m
                        },
                        new
                        {
                            Id = "5fb3f4d8-848e-497e-b413-75490bc79ac9",
                            Deleted = false,
                            Group = "Electrical Repairs",
                            Name = "Ignition Module Testing And Replacing",
                            Value = 55.40m
                        },
                        new
                        {
                            Id = "29ea5602-670d-456a-b3d7-28dbea5d799a",
                            Deleted = false,
                            Group = "Fuel Injection",
                            Name = "Leaky Fuel Injector Repairs",
                            Value = 35.60m
                        },
                        new
                        {
                            Id = "a6292aff-162f-4dc0-95ed-3926a9fbe1e3",
                            Deleted = false,
                            Group = "Fuel Injection",
                            Name = "Fuel Hose Replacement",
                            Value = 55.0m
                        },
                        new
                        {
                            Id = "ac0f7bdd-4089-4ffc-bfd5-02f60e391f9a",
                            Deleted = false,
                            Group = "Fuel Injection",
                            Name = "Fuel Pump Replacement",
                            Value = 15.50m
                        },
                        new
                        {
                            Id = "f83a2dc8-6a3d-429c-b1f6-9f3f14f0102e",
                            Deleted = false,
                            Group = "Fuel Injection",
                            Name = "Sensor Testing",
                            Value = 14.0m
                        },
                        new
                        {
                            Id = "a8178169-e0f5-469a-ba5c-fb06dad5cd86",
                            Deleted = false,
                            Group = "Suspension and Steering",
                            Name = "Suspension Checks",
                            Value = 25.30m
                        },
                        new
                        {
                            Id = "f7dc5276-13fc-44a4-99b3-c98ed31bc87c",
                            Deleted = false,
                            Group = "Suspension and Steering",
                            Name = "Shock Absorber Replacement",
                            Value = 45.80m
                        },
                        new
                        {
                            Id = "7e7c2c32-ec06-4ebb-9c61-bd9b17ec5022",
                            Deleted = false,
                            Group = "Suspension and Steering",
                            Name = "Ball Joints and Tie Rod End Replacement",
                            Value = 35.0m
                        },
                        new
                        {
                            Id = "451a842e-b310-49b5-87aa-0581e6110923",
                            Deleted = false,
                            Group = "Suspension and Steering",
                            Name = "Suspension Springs Replaced ",
                            Value = 45.90m
                        },
                        new
                        {
                            Id = "d2f31fc1-670c-401d-9de8-119788d7d359",
                            Deleted = false,
                            Group = "Suspension and Steering",
                            Name = "Wheel Alignment",
                            Value = 16.50m
                        },
                        new
                        {
                            Id = "90400ec9-1173-4fa3-8612-dfd68fb22302",
                            Deleted = false,
                            Group = "Suspension and Steering",
                            Name = "Front Wheel Bearing Replacement",
                            Value = 55.40m
                        },
                        new
                        {
                            Id = "89d9138b-52ca-4cf3-b272-e83f77247813",
                            Deleted = false,
                            Group = "Suspension and Steering",
                            Name = "Rear Axle Bearings And Seals Replacement",
                            Value = 45.0m
                        },
                        new
                        {
                            Id = "16325388-18cf-469c-8ec6-051d7101d299",
                            Deleted = false,
                            Group = "Cooling System",
                            Name = "Thermofan Replacement",
                            Value = 23.0m
                        },
                        new
                        {
                            Id = "0ca99583-d94b-4c73-a699-8f10cae1cb8a",
                            Deleted = false,
                            Group = "Cooling System",
                            Name = "Fan & Drive Belt Replacment",
                            Value = 14.20m
                        },
                        new
                        {
                            Id = "f2b37fa3-6294-463a-91a7-46b8435b96eb",
                            Deleted = false,
                            Group = "Cooling System",
                            Name = "Cooling System Leakage Tests",
                            Value = 18.0m
                        },
                        new
                        {
                            Id = "09000dbd-48aa-45b9-ac73-5c938b1dfe66",
                            Deleted = false,
                            Group = "Cooling System",
                            Name = "Radiator Replacement",
                            Value = 58.05m
                        },
                        new
                        {
                            Id = "1d8dc03e-094b-4dc6-9214-2ac923d1d6f5",
                            Deleted = false,
                            Group = "Cooling System",
                            Name = "Water Pump Replacement",
                            Value = 25.10m
                        },
                        new
                        {
                            Id = "42b6c4b0-b8f4-4d77-b928-09003710e414",
                            Deleted = false,
                            Group = "Cooling System",
                            Name = "Heater Hose and Heater Tap Replacement",
                            Value = 35.40m
                        },
                        new
                        {
                            Id = "0d7497a1-5492-4896-afeb-30a6a2f0c4f4",
                            Deleted = false,
                            Group = "Cooling System",
                            Name = "Coolant Flush Replacement",
                            Value = 25.0m
                        },
                        new
                        {
                            Id = "251e37cf-eced-444c-8302-35545794305f",
                            Deleted = false,
                            Group = "Cooling System",
                            Name = "Radiator Hose, Thermostat Replacement",
                            Value = 54.10m
                        },
                        new
                        {
                            Id = "74ed02ae-2a34-4c77-81a6-cadc21d3d270",
                            Deleted = false,
                            Group = "Engine",
                            Name = "Car Cylinder Head Reconditioning",
                            Value = 156.50m
                        },
                        new
                        {
                            Id = "89156bc0-ecf3-4c26-afb6-cf7d73049672",
                            Deleted = false,
                            Group = "Engine",
                            Name = "Compression Tests",
                            Value = 46.10m
                        },
                        new
                        {
                            Id = "ecb88295-1f98-4f09-810d-c560e58e132f",
                            Deleted = false,
                            Group = "Engine",
                            Name = "Vacuum Testing",
                            Value = 26.0m
                        },
                        new
                        {
                            Id = "56174cbb-a731-4448-bc7d-b3c54659349e",
                            Deleted = false,
                            Group = "Engine",
                            Name = "Throtle Body Cleaning",
                            Value = 36.40m
                        },
                        new
                        {
                            Id = "e4edb081-dad3-4528-8e6c-92e676756467",
                            Deleted = false,
                            Group = "Engine",
                            Name = "Gas Analyser Checks",
                            Value = 19.0m
                        },
                        new
                        {
                            Id = "94d1dabe-09e2-4cac-90f0-3acd8ba26954",
                            Deleted = false,
                            Group = "Engine",
                            Name = "Manifold Gasket & Exhaust Repairs",
                            Value = 24.60m
                        },
                        new
                        {
                            Id = "44d3204b-d708-46e3-b6d3-831e97a74409",
                            Deleted = false,
                            Group = "Engine",
                            Name = "Car Points Replacement",
                            Value = 35.20m
                        },
                        new
                        {
                            Id = "095965b2-4502-4e34-a4d2-8741601b3717",
                            Deleted = false,
                            Group = "Engine",
                            Name = "Timing Belt Replacement",
                            Value = 14.20m
                        },
                        new
                        {
                            Id = "af4b1455-c98f-42d7-a81c-42b40487d0c7",
                            Deleted = false,
                            Group = "Engine",
                            Name = "Prepurchase Inspections",
                            Value = 55.10m
                        });
                });

            modelBuilder.Entity("GarageManagementSystem.Models.Vehicle", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("EngineType")
                        .HasColumnType("int");

                    b.Property<string>("Licence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Make")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Vehicle");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "e3d4f4a2-1c98-486d-bc8d-1773e3766bb4",
                            ConcurrencyStamp = "7d36eb1e-f28b-4984-b8f8-ccd44b6f11c9",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "b09f1e6f-0574-4589-9c08-44d22a208054",
                            ConcurrencyStamp = "aaeb9d55-3071-40d0-8d46-8c1b121751fb",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        },
                        new
                        {
                            Id = "ef38b05c-8be4-4162-a344-1eec9d231943",
                            ConcurrencyStamp = "2d137420-c535-4fb7-9f32-801e44f4c7d4",
                            Name = "Mechanic",
                            NormalizedName = "MECHANIC"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "d42eb8c8-2232-406b-9bc0-3859863f064c",
                            RoleId = "e3d4f4a2-1c98-486d-bc8d-1773e3766bb4"
                        },
                        new
                        {
                            UserId = "160453a8-8e19-4f70-9b61-3f6f37d82a3a",
                            RoleId = "ef38b05c-8be4-4162-a344-1eec9d231943"
                        },
                        new
                        {
                            UserId = "cab9f1df-6d5c-40ae-b05a-be0d0d379f55",
                            RoleId = "ef38b05c-8be4-4162-a344-1eec9d231943"
                        },
                        new
                        {
                            UserId = "990d5d6b-e4b1-4978-accc-5065754d1632",
                            RoleId = "ef38b05c-8be4-4162-a344-1eec9d231943"
                        },
                        new
                        {
                            UserId = "98857515-b584-464e-850c-5047904de7f7",
                            RoleId = "ef38b05c-8be4-4162-a344-1eec9d231943"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("GarageManagementSystem.Models.Booking", b =>
                {
                    b.HasOne("GarageManagementSystem.Models.ApplicationUser", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GarageManagementSystem.Models.ApplicationUser", "Mechanic")
                        .WithMany()
                        .HasForeignKey("MechanicId");

                    b.HasOne("GarageManagementSystem.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Mechanic");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("GarageManagementSystem.Models.Invoice", b =>
                {
                    b.HasOne("GarageManagementSystem.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("GarageManagementSystem.Models.InvoicePart", b =>
                {
                    b.HasOne("GarageManagementSystem.Models.Invoice", null)
                        .WithMany("InvoiceParts")
                        .HasForeignKey("InvoiceId");
                });

            modelBuilder.Entity("GarageManagementSystem.Models.InvoiceService", b =>
                {
                    b.HasOne("GarageManagementSystem.Models.Invoice", null)
                        .WithMany("InvoiceServices")
                        .HasForeignKey("InvoiceId");
                });

            modelBuilder.Entity("GarageManagementSystem.Models.Vehicle", b =>
                {
                    b.HasOne("GarageManagementSystem.Models.ApplicationUser", null)
                        .WithMany("Vehicles")
                        .HasForeignKey("ApplicationUserId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GarageManagementSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GarageManagementSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GarageManagementSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GarageManagementSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GarageManagementSystem.Models.ApplicationUser", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("GarageManagementSystem.Models.Invoice", b =>
                {
                    b.Navigation("InvoiceParts");

                    b.Navigation("InvoiceServices");
                });
#pragma warning restore 612, 618
        }
    }
}
